sa/urls.py
from django.urls import path

from . import views

app_name = "sa"
urlpatterns = [
    path('', views.index, name='index'),
    path('ifttt', views.ifttt, name='ifttt'),
    path('ifttt/<str:user_id>', views.ifttt, name='ifttt'),
    path('assistant/<str:typ>', views.assistant, name='assistant'),
    path('assistant/<str:typ>/<str:user_id>', views.assistant, name='assistant'),
    path('add_ifttt/<str:user_id>', views.add_ifttt, name='add_ifttt'),
    path('execute_query/<str:typ>/<str:user_id>', views.execute_query, name="execute_query"),
]

smartassistant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('sa.urls')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sa/models.py
from django.db import models

# User
class User(models.Model):
	userId = models.CharField(max_length=100)
	
	def __str__(self):
		return self.userId

# Actuator Brand
class Brand(models.Model):
	name = models.CharField(max_length=100)
	logo = models.ImageField(upload_to="brand_logos/")
	
	def __str__(self):
		return self.name

# Actuator
class Actuator(models.Model):
	brand = models.ForeignKey(Brand, on_delete = models.CASCADE)
	name = models.CharField(max_length=100)
	minimum = models.IntegerField(default=0)
	maximum = models.IntegerField(default=100)
	units = models.CharField(max_length=15, default="%")
	
	def __str__(self):
		return str(self.brand) + "-" + self.name
	
# This
class This(models.Model):
	originalcommand = models.CharField(max_length=1000)
	command = models.CharField(max_length=1000)
	variable = models.CharField(max_length=100)
	category = models.CharField(max_length=100)
	
	def __str__(self):
		return self.originalcommand

# That
class That(models.Model):
	actuator = models.ForeignKey(Actuator, on_delete = models.CASCADE)
	value = models.IntegerField(default=50)
	
	def __str__(self):
		return str(self.actuator) + ": " + str(self.value)

# Rules
class Rule(models.Model):
	# IF this then that
	user = models.ForeignKey(User, on_delete = models.CASCADE)
	this = models.ForeignKey(This, on_delete = models.CASCADE)
	that = models.ForeignKey(That, on_delete = models.CASCADE)
	
	def __str__(self):
		return "IF " + str(self.this) + " THEN " + str(self.that)

sa/views.py
from unicodedata import category
from django.shortcuts import render
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from sa.models import Actuator, This, That, Rule, User
import uuid
from util.precisiation import Precisiation
from sentence_transformers import SentenceTransformer
from scipy import spatial
import spacy
import editdistance

nlp = spacy.load('en_core_web_sm',disable=['ner','textcat'])
# model_sbert = SentenceTransformer('sentence-transformers/all-mpnet-base-v2')
model_sbert = SentenceTransformer('all-MiniLM-L12-v2')

# Create your views here.
def index(request):
    return HttpResponse("Hello. You're at the smart assistant index.")


def ifttt(request, rule = None, user_id = None):
    new_id = False
    if user_id == None:
        user_id = request.COOKIES.get("Django_test_cookie")
        if user_id is None:
            # Cookie is not set, set it to random user ID
            new_id = True
            user_id = uuid.uuid4()

    actuators = Actuator.objects.all()

    context = {"user_id" : user_id, "actuators" : actuators, "rule": rule}
    response = render(request, "sa/ifttt.html", context)
    
    if new_id:
        response.set_cookie("Django_test_cookie", user_id)

    return response

def assistant(request, typ = "A", user_id = None, query = None, message = None):
    new_id = False
    if user_id == None:
        user_id = request.COOKIES.get("Django_test_cookie")
        if user_id is None:
            # Cookie is not set, set it to random user ID
            new_id = True
            user_id = uuid.uuid4()

    context = {"user_id" : user_id, "message": message, "query": query, "typ": typ}
    response = render(request, "sa/assistant.html", context)
    
    if new_id:
        response.set_cookie("Django_test_cookie", user_id)

    return response

def add_ifttt(request, user_id):
    this_sentence = request.POST["this"]
    that_actuator = request.POST["actuator"]
    that_value = request.POST["value"]
    
    tokens = nlp(this_sentence)

    var = ""
    for i,token in enumerate(tokens):
        if ((token.tag_ in ["JJ", "JJR", "JJS", "PDT", "RB", "RBR", "RBS"] or 
            (var == "" and i == len(tokens)-1 and (nlp(token.text)[0].pos_ == "ADJ" or nlp(token.text)[0].pos_ == "ADV"))) and 
            token.text not in ["here", "there", "in"]):
            var = token.text

    p = Precisiation()
    cat = p.get_category([var])

    this = This(originalcommand = this_sentence, command = this_sentence.replace(var, cat), variable = var, category = cat)
    act = Actuator.objects.get(id=that_actuator)
    that = That(actuator = act, value = that_value)
    this.save()
    that.save()

    try:
        user = User.objects.get(userId = user_id)
    except ObjectDoesNotExist:
        user = User(userId = user_id)
        user.save()

    rule = Rule(this = this, that = that, user = user)
    rule.save()

    return ifttt(request, f"IF SAY '{this_sentence}' THEN SET {act} to {that_value} {act.units}")

def execute_query(request, typ = "A", user_id=None):
    # If the query has been done to the assistant A (the fuzzy one!)
    if typ == "A":
        query = request.POST["query"]

        # Tokenize and find POS
        tokens = nlp(query)

        adj = ""
        
        for i,token in enumerate(tokens):
            print(token.text, token.pos_)
            if ((token.tag_ in ["JJ", "JJR", "JJS", "PDT", "RB", "RBR", "RBS"] or 
                (adj == "" and i == len(tokens)-1 and (nlp(token.text)[0].pos_ == "ADJ" or nlp(token.text)[0].pos_ == "ADV"))) and 
                token.text not in ["here", "there", "in"]):
                    print(token)
                    adj = token.text

        # Remove POS and encode with sBERT
        p = Precisiation(db_file="./synonyms.db")
        cat = p.get_category([adj])
        query_c = query.replace(adj, cat)
        encoded_query = model_sbert.encode(query_c)

        print(encoded_query.shape)

        # Find best matching query, giving the priority to those with the same category
        maxi = ("", 0)
        for r in Rule.objects.filter(user__userId = user_id).filter(this__category = cat):
            s = r.this.command
            sim = 1 - spatial.distance.cosine(model_sbert.encode(s),encoded_query)
            if sim > maxi[1]:
                maxi = (r, sim)

        # If nothing good enough was found, try to search also in other categories
        if maxi[1] < 0.5:
            maxi = ("", 0)
            for r in Rule.objects.filter(user__userId = user_id):
                s = r.this.command
                sim = 1 - spatial.distance.cosine(model_sbert.encode(s),encoded_query)
                if sim > maxi[1]:
                    maxi = (r, sim)
            
            # If no matching category, return error and let user repeat the query
            if maxi[1] < 0.5:
                # Return message unknown command and let try another query
                return assistant(request, typ = typ, query = query, message = "Unknown query, please try with another wording.")

        # Precisiate the word from the ground truth and that from the query
        adj_gt = maxi[0].this.variable
        cat_gt = maxi[0].this.category
        target_gt = maxi[0].that.value
        target_range = (maxi[0].that.actuator.minimum, maxi[0].that.actuator.maximum)
        target_units = maxi[0].that.actuator.units

        prec_gt = p.precisiate_v2(adj_gt, cat_gt)

        # Compute max distance between elements
        #distmax = 4 / (1 + prec_gt[0]) * abs(target_gt - (target_range[0] + target_range[1]) / 2)
        #distmax = 2 / (prec_gt[0]) * abs(target_gt - (target_range[0] + target_range[1]) / 2)
        distmax = abs(target_range[1]-target_range[0])
        #distmax = abs(2 * abs(target_gt-target_range[0]) - abs(target_range[1]-target_range[0]))

        print(f"Distmax: {distmax}")

        if adj.lower() == "medium":
            prec = (0.5,)
        else:
            prec = p.precisiate_v2(adj, cat)

        dist = abs(prec[0]-prec_gt[0])*distmax

        # Choose direction based on the position of the gt wrt the mid
        if prec_gt[0] >= 0.5:
            sgn = -1
        else:
            sgn = 1

        # Compute target result based on the distance between the different precisiated values, scaled to match the new scale
        target_result = target_gt + sgn * dist if (target_gt + sgn * dist >= target_range[0] - abs(target_range[1]-target_range[0])*0.2
            and target_gt + sgn * dist < target_range[1] + abs(target_range[1]-target_range[0])*0.2) else target_gt - sgn * dist

        mi, ma = min(target_range[0], target_range[1]), max(target_range[0], target_range[1])
        target_result = max(min(ma, target_result), mi)

        target_result = round(target_result, 1)

        return assistant(request, typ = typ, user_id = user_id, query = query, message =f"Okay, I will set {maxi[0].that.actuator} to {target_result} {target_units}")
    
    # The request has been done to the "normal" assistant
    else:
        query = request.POST["query"]

        # Find best matching query with string edit distance
        mini = ("", 100)
        for r in Rule.objects.all():
            s = r.this.originalcommand
            dist = editdistance.eval(s, query)

            if dist < mini[1]:
                mini = (r, dist)

        # If nothing good enough was found, unknown query, otherwise return matched query
        if mini[1] > 4:
            return assistant(request, typ = typ, user_id = user_id, query = query, message = "Unknown query, please try with another wording.")

        target_gt = mini[0].that.value
        target_units = mini[0].that.actuator.units

        return assistant(request, typ = typ, user_id = user_id, query = query, message =f"Okay, I will set {mini[0].that.actuator} to {target_gt} {target_units}")

sa/templates/sa/assistant.html
<!DOCTYPE html>
<html>
<head>
<title>Assistant</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
@media (min-width: 801px){
    .w3-container {
        position:absolute;
        top: 50%;
        left:50%;
        width: 40%;
        margin: -20% 0 0 -20%;
    }
}

@media (max-width: 800px){
    .w3-container{
        position:absolute;
        top: 50%;
        width: 100%;
        margin-top: -20%;
    }
}
</style>
</head>
<body class="w3-light-grey">
    <div class="w3-container w3-white w3-padding-16">
        <form action="{% url 'sa:execute_query' typ user_id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>Your query: </h1></legend>
                <textarea class="w3-input w3-border" name="query"></textarea>
            </fieldset>
            <input class="w3-button w3-dark-grey" type="submit" value="Execute query">
        </form>
        {% if query %}
        <p> > <i>{{ query }}</i></p>
        {% endif %}
        {% if message %}
        <p> > <b>{{ message }}</b></p>
        {% endif %}
    </div>
</body>

sa/templates/sa/ifttt.html
<!DOCTYPE html>
<html>
<head>
<title>IFTTT Rule</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
@media (min-width: 801px){
    .w3-container {
        position:absolute;
        top: 50%;
        left:50%;
        width: 40%;
        margin: -20% 0 0 -20%;
    }
}

@media (max-width: 800px){
    .w3-container{
        position:absolute;
        top: 50%;
        width: 100%;
        margin-top: -20%;
    }
}

input {
  vertical-align: middle;
  margin: 5px 10px 5px 0;
  padding: 10px;
  background-color: #fff;
  border: 1px solid #ddd;
}
</style>
<script type="text/javascript">
    units = {
        {% for actuator in actuators %}
            "{{ actuator.id }}" : "{{ actuator.units }}",
        {% endfor %}
    }

    function change_units(){
        var x = document.getElementById("mySelect").value;
        console.log(x)
        document.getElementById("units").innerHTML = units[x];
    }
</script>
</head>
<body class="w3-light-grey">
    <div class="w3-container w3-white w3-padding-16">
        <form action="{% url 'sa:add_ifttt' user_id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend><h1>New IFTTT rule</h1></legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <h2>IF say : </h2>
            <textarea class="w3-input w3-border" name="this" required></textarea>
            <h2>THEN : </h2>
            <a> set </a><select class="w3-input w3-border" id="mySelect" onchange="change_units()" name="actuator" required>
                <option value="" selected disabled hidden>Choose here</option>
                {% for actuator in actuators %}
                    <option value="{{ actuator.id }}">{{ actuator }}</option>
                {% endfor %}
            </select>
            <a> value to    </a>
            <input style="width:100px;" name="value" type="number" required></input>   <a id="units"></a>
        </fieldset>
        <input class="w3-button w3-dark-grey" type="submit" value="Save rule">
        </form>
        {% if rule %}
        <p>Rule: "<b>{{ rule }}</b>" successfully added!</p>
        {% endif %}
    </div>
</body>